name: CICD
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2

    - name: Start Tracee profiling in background
      uses: aquasecurity/tracee-action@5723c0a6d55aa74a749394d5a35ff653819a061f

    - name: Verify dependencies
      run: go mod verify

    - name: Run tests
      run: go test -race -vet=off ./...

    - name: Build
      run: go build -o app -v ./...

    - name: Fake upload
      uses: josedonizetti/upload-fake-action@v0.1.0

    - name: Stop and Check Tracee results and create a PR
      uses: aquasecurity/tracee-action@402c713c3a1258a495cf097891eb160a48c617ba
      with:
        create-pr: "true"
        fail-on-diff: "true"
