name: CICD
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2

    - name: Start Tracee profiling in background
      uses: aquasecurity/tracee-action@e31468fa81490f1f5ed9651f5186c55141c4884e

    - name: Build
      run: docker build -f Dockerfile -t test:tag . &

    - name: ps
      run: for i in {1..4}; do ps -efj; done

    - name: Stop and Check Tracee results and create a PR
      uses: aquasecurity/tracee-action@8d16edbf40c7c125e4da3e2e4e1bc22e63b55810
      with:
        create-pr: "true"
        fail-on-diff: "true"
