name: CICD
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2

    - name: Start Tracee profiling in background
      uses: aquasecurity/tracee-action@784de9f19f2e7ba7f1ec65b65e9fa58a97825814

    - name: Verify dependencies
      run: go mod verify

    - name: Run tests
      run: go test -race -vet=off ./...

    - name: Build
      run: go build -o app -v ./...

    - name: Fake upload
      uses: josedonizetti/upload-fake-action@v0.1.0

        #- name: Setup upterm session
        #uses: lhotari/action-upterm@v1

    - name: Stop and Check Tracee results and create a PR
      uses: aquasecurity/tracee-action@6f44b2a2471569f19972497309dab1c61e2fbca2
      with:
        create-pr: "true"
        fail-on-diff: "true"
