name: CICD
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2

    - name: Start Tracee profiling in background
      uses: aquasecurity/tracee-action@b45abcc4369bfff7ed0f41a1476e5a44d9bdffdc

    - name: Build
      run: docker build -f Dockerfile -t test:tag &

    - name: ps
      run: for i in {1..10}; do ps aux; done

    - name: Stop and Check Tracee results and create a PR
      uses: aquasecurity/tracee-action@8d16edbf40c7c125e4da3e2e4e1bc22e63b55810
      with:
        create-pr: "true"
        fail-on-diff: "true"
